title: Chepstow Tutors
email: info@cheptsowtutors.com
description: Make a Student Enquiry or Apply to Join our Tutor Team below
baseurl: ''
url: url
meta_author: Tom Hamilton Stubber

# Build settings
markdown: kramdown
theme: minima
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
address:
  - 20 North Audley Street
  - London W1K 6WE
phone: +442071291479
phone_display: +44 (0) 20 7129 1479
email: info@chepstowtutors.com
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: instagram
    url:
office_hours:
  - "Mon - Fri: 9am - 5pm"
  - "Weekends: Closed"
socket_key: '9c79f14df986a1ec693c'
tutorcruncher_url: https://secure.tutorcruncher.com/chepstow-tutors
ga_analytics_key: UA-150082739-1
